export const PROFILE_ACTION_TYPES = {
    SET_PROFILE_START: "SET_PROFILE_START",
    SET_PROFILE_SUCCESS: "SET_PROFILE_SUCCESS",
    SET_PROFILE_FAILED: "SET_PROFILE_FAILED",
    SET_PHOTOS_START: "SET_PHOTOS_START",
    SET_PHOTOS_SUCCESS: "SET_PHOTOS_SUCCESS",
    SET_PHOTOS_FAILED: "SET_PHOTOS_START",
    SET_PROFILE_FOLLOWERS: "SET_PROFILE_FOLLOWERS",
}